// Auto-Generated by FAKE; do not edit
namespace Garnet.AssemblyInfo
open System.Reflection

[<assembly: AssemblyTitleAttribute("Garnet")>]
[<assembly: AssemblyProductAttribute("Garnet")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2019 Ben Carruthers")>]
[<assembly: AssemblyDescriptionAttribute("F# game composition library")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Garnet"
    let [<Literal>] AssemblyProduct = "Garnet"
    let [<Literal>] AssemblyCopyright = "Copyright © 2019 Ben Carruthers"
    let [<Literal>] AssemblyDescription = "F# game composition library"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
