// Auto-Generated by FAKE; do not edit
namespace Garnet.Samples.Flocking.AssemblyInfo
open System.Reflection

[<assembly: AssemblyTitleAttribute("Garnet.Samples.Flocking")>]
[<assembly: AssemblyProductAttribute("Garnet.Samples.Flocking")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2019 Ben Carruthers")>]
[<assembly: AssemblyDescriptionAttribute("Game composition library")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Garnet.Samples.Flocking"
    let [<Literal>] AssemblyProduct = "Garnet.Samples.Flocking"
    let [<Literal>] AssemblyCopyright = "Copyright © 2019 Ben Carruthers"
    let [<Literal>] AssemblyDescription = "Game composition library"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
